### ISSUE TITLE
Version tags are published as new modules on nest.land

### ISSUE THREAD

**Issue by GJZwiers** [nestdotland/eggs#138]
My module's tags are being uploaded to nest.land as entirely new packages for some reason. This is my release pipeline:

```
name: publish egg

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.13.x
      - name: Release
        run: |
          deno install -Af --unstable https://x.nest.land/eggs@0.3.10/eggs.ts
          eggs link ${{ secrets.NESTAPIKEY }}
          eggs publish --yes --no-check --version $(git describe --tags $(git rev-list --tags --max-count=1))

```

egg.json:

```json
{
  "name": "mod",
  "entry": "./mod.ts",
  "description": "Start a new Deno module",
  "unstable": true,
  "version": "v2.2.6",
  "files": [
    "./**/*.ts",
    "./README.md",
    "./LICENSE"
  ],
  "checkFormat": "deno fmt",
  "checkInstallation": true,
  "checkTests": false,
  "check": true,
  "homepage": "https://github.com/GJZwiers/mod",
  "ignore": [],
  "unlisted": false
}

```
